spring:
  profiles:
    active: test

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  datasource:
    url: jdbc:mysql://chunsodb.c04b2rx0gbkh.ap-northeast-2.rds.amazonaws.com:3306/olive_bakery?useSSL=false&serverTimezone=Asia/Seoul
    username: chunso
    password: alswjd96
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  resources:
    static-locations: file:///C:\Users\Kimyunsang\Desktop\spring\imageTest

logging:
  level:
    root: info

server:
  port: 8080
